AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Events:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Events
      AttributeDefinitions:
        - AttributeName: aggregateId
          AttributeType: S
        - AttributeName: version
          AttributeType: N
      KeySchema:
        - AttributeName: aggregateId
          KeyType: HASH  # Partition key
        - AttributeName: version
          KeyType: RANGE # Sort key
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE  # Configura para observar las nuevas imágenes de los eventos
      SSESpecification:
        SSEEnabled: true  # Habilita la encriptación en reposo para mayor seguridad

  Idempotency:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Idempotency
      AttributeDefinitions:
        - AttributeName: hashCommand
          AttributeType: S
        - AttributeName: aggregateId
          AttributeType: S
      KeySchema:
        - AttributeName: hashCommand
          KeyType: HASH  # Partition key
        - AttributeName: aggregateId
          KeyType: RANGE # Sort key
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true

  MaxProductPerFranchiseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MaxProductPerFranchise
      AttributeDefinitions:
        - AttributeName: franchiseId
          AttributeType: S
        - AttributeName: branchId
          AttributeType: S
      KeySchema:
        - AttributeName: franchiseId
          KeyType: HASH  # Partition key
        - AttributeName: branchId
          KeyType: RANGE # Sort key
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true  # Encriptación en reposo